const jokes = [
    "Why don’t scientists trust atoms? Because they make up everything!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "What do you call fake spaghetti? An impasta.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why couldn't the bicycle stand up by itself? It was two-tired.",
    "What did the grape do when he got stepped on? Nothing but let out a little wine!",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "I would avoid the sushi if I was you. It’s a little fishy.",
    "Want to hear a joke about construction? I’m still working on it.",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels.",
    "What do you call a fish with no eyes? A fsh.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "Why don’t oysters donate to charity? Because they are shellfish.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why don’t dinosaurs talk? Because they’re dead.",
    "What do you call a factory that makes good products? A satisfactory.",
    "Why did the math book look sad? Because it had too many problems.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why are ghosts bad at lying? Because you can see right through them.",
    "Why don’t some fish play piano? Because you can’t tuna fish.",
    "Why did the scarecrow get promoted? He was outstanding in his field.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "Why don’t they play poker in the jungle? Too many cheetahs.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "Why did the picture go to jail? Because it was framed.",
    "What do you call an alligator in a vest? An investigator.",
    "Why did the music teacher go to jail? Because she got caught with the notes.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why can’t you give Elsa a balloon? Because she will let it go.",
    "Why don’t crabs give to charity? Because they’re shellfish.",
    "Why did the cow go to space? To see the moooon.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why did the man put his money in the blender? He wanted to make liquid assets.",
    "Why did the bicycle fall over? It was two-tired.",
    "Why don’t skeletons ever go trick or treating? Because they have no-body to go with.",
    "What do you call a pig that does karate? A pork chop.",
    "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
    "Why can’t you hear a pterodactyl in the bathroom? Because it has a silent pee.",
    "What did one hat say to the other? Stay here, I’m going on ahead.",
    "Why don’t programmers like nature? It has too many bugs.",
    "Why don’t some couples go to the gym? Because some relationships don’t work out.",
    "What’s orange and sounds like a parrot? A carrot.",
    "Why did the man put his money in the blender? He wanted to make liquid assets.",
    "Why was the math book sad? It had too many problems.",
    "What do you call a shoe made of a banana? A slipper.",
    "Why are ghosts bad at lying? Because you can see right through them.",
    "Why don’t they play poker in the jungle? Too many cheetahs.",
    "Why did the chicken go to the seance? To talk to the other side.",
    "What did the duck say when it bought lipstick? Put it on my bill.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "Why did the scarecrow win an award? He was outstanding in his field.",
    "Why don’t some fish play piano? Because you can’t tuna fish.",
    "What do you get when you cross a snowman with a vampire? Frostbite.",
    "Why don’t you ever see elephants hiding in trees? Because they’re so good at it.",
    "What’s a skeleton’s least favorite room in the house? The living room.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "Why was the broom late? It swept in.",
    "Why did the mushroom go to the party alone? Because he’s a fungi.",
    "Why don’t seagulls fly over the bay? Because then they’d be bay-gulls.",
    "What do you call fake spaghetti? An impasta.",
    "What do you call a dog magician? A labracadabrador.",
    "Why did the orange stop? It ran out of juice.",
    "Why can’t your nose be 12 inches long? Because then it would be a foot.",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "Why don’t oysters donate to charity? Because they are shellfish.",
    "Why did the scarecrow get promoted? Because he was outstanding in his field.",
    "Why did the music teacher go to jail? Because she got caught with the notes.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call a factory that makes good products? A satisfactory.",
    "Why did the cow go to space? To see the moooon.",
    "Why was the belt arrested? For holding up the pants.",
    "Why did the scarecrow get promoted? He was outstanding in his field.",
    "What do you call an alligator in a vest? An investigator.",
    "Why can’t you give Elsa a balloon? Because she will let it go.",
    "Why did the bicycle fall over? It was two-tired.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why don’t crabs give to charity? Because they’re shellfish.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why did the picture go to jail? Because it was framed.",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "What do you call fake spaghetti? An impasta.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why don’t dinosaurs talk? Because they’re dead.",
    "Why was the broom late? It swept in.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "Why did the man put his money in the blender? He wanted to make liquid assets."
];
const func=(a)=>{
    return a
}
document.write(jokes[Math.floor(Math.random()*jokes.length,func)])